### ISSUE TITLE
can i be a collaborator ?

### ISSUE THREAD

**Issue by Manu2806** [Lumphie/Fairytale_test#19]
@Lumphie

**Comment by Lumphie** [comment]
Added, just accept the invitation and then close this issue!

**Comment by Lumphie** [comment]
@Manu2806, you're not yet a collaborator, accept the invitation before closing this issue

**Comment by Lumphie** [comment]
https://github.com/Lumphie/Fairytale_test/invitations

**Comment by Lumphie** [comment]
@Manu2806
